AllCops:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/SpaceBeforeSemicolon:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true
