AllCops:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/SpaceBeforeSemicolon:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%w': '()'
